[tool.poetry]
name = "flask-web-demo"
version = "0.1.0"
description = "Flask Hello Web"
authors = ["Damon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
